name: flutter_template
description: A barebone flutter template that will get you up and running in no time.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_navigation_generator_annotations: ^1.0.1
  impaktfull_architecture:
    git: 
      url: git@github.com:Impaktfull/flutter_architecture.git
      ref: 2ddbb15

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_navigation_generator: ^1.0.3
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true